#!/usr/bin/env bash
# Idempotent dependency + local-service setup for the Soyla dev environment.
# Runs after the repo is checked out. Safe to run repeatedly.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

PG_VERSION=16
PG_CLUSTER=main

echo "==> Installing system packages (postgresql, redis, ffmpeg, python venv)"
export DEBIAN_FRONTEND=noninteractive
sudo apt-get update -qq
sudo apt-get install -y --no-install-recommends \
  postgresql postgresql-contrib redis-server ffmpeg \
  python3-venv python3-pip

echo "==> Creating Python virtualenv and installing requirements"
if [ ! -x ".venv/bin/python" ]; then
  python3 -m venv .venv
fi
# shellcheck disable=SC1091
. .venv/bin/activate
python -m pip install --upgrade pip
pip install -r requirements.txt
pip install pytest

echo "==> Ensuring PostgreSQL is running (needed to create dev role/db)"
sudo pg_ctlcluster "$PG_VERSION" "$PG_CLUSTER" start 2>/dev/null || true
for i in $(seq 1 30); do
  if sudo -u postgres pg_isready -q 2>/dev/null; then break; fi
  sleep 1
done

echo "==> Configuring dev database role/db (idempotent)"
sudo -u postgres psql -v ON_ERROR_STOP=1 -c "ALTER USER postgres WITH PASSWORD 'postgres';"
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='dating_bot'" | grep -q 1; then
  sudo -u postgres createdb dating_bot
fi

echo "==> Stopping PostgreSQL so environment snapshots don't capture a stale postmaster.pid"
# start.sh brings the cluster back up on every boot; leaving it running here would
# bake a stale pid file into any environment-build snapshot.
sudo pg_ctlcluster "$PG_VERSION" "$PG_CLUSTER" stop 2>/dev/null || true

echo "==> Creating local .env if missing (never overwrites an existing one)"
if [ ! -f .env ]; then
  cat > .env <<'ENVEOF'
# Local dev .env (generated by .cursor/install.sh; gitignored).
# A real Telegram bot token is only required to run the live aiogram bot.
# The API imports/runs fine with this placeholder. To run the live bot or
# enable real audio/video, set BOT_TOKEN / LIVEKIT_* as Cloud Agent secrets.
BOT_TOKEN=dev-placeholder-token
WEBAPP_URL=

POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=dating_bot
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/dating_bot

REDIS_URL=redis://localhost:6379/0

MIN_AGE=12
MAX_AGE_GAP=5

LIVEKIT_URL=
LIVEKIT_API_KEY=
LIVEKIT_API_SECRET=

ADMIN_IDS=
GEMINI_API_KEY=
YTDLP_COOKIES_FILE=
ENVEOF
fi

echo "==> Install complete"
